services:
  postgres:
    image: 'postgres:latest'
    container_name: db
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - db-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 1234
    ports:
      - "1234:1234"
    networks:
      - db-net
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  db-net:
volumes:
  postgres_data:
  pgadmin_data: